version: "3.8"
services:
  postgres:
    container_name: gilbert-postgres
    image: postgres:14.5
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - "./etc/docker/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro"
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data:
